version: "3"
   
services:
  # db:
  #   restart: always
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   ports:
  #       - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    volumes: 
      - ./django/Hos:/Hos
  
    # depends_on: 
    #   - db

